version: 3.1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- ps: msbuild .\src /t:restore,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /p:PublishRepositoryUrl=true /verbosity:minimal
test_script:
- ps: dotnet test .\src\NLog.Targets.Redis.Tests\

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: 'src\**\*.nupkg'
  - path: 'src\**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: F4Be+YAhVriUv2zHBE38iTqS55PFnxVbbNbpQDS90zqPQFgT7vVeqqQ/BGoQYhv8
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: master
