version: 3.1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: msbuild .\src /t:restore,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /p:PublishRepositoryUrl=true /verbosity:minimal
test_script:
- ps: dotnet test .\src\NLog.Targets.Redis.Tests\

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: 'src\**\*.nupkg'
  - path: 'src\**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 0IpLU3V1eXUsWCRjKGuyyeuLQYfFpv6BAoIihFQryuYZsOWVvxUBvQOC0dOL2n
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: master
