version: 3.0.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  # AssemblyVersion should not be touch by the patcher.
  # Per https://github.com/NLog/NLog/issues/1765#issuecomment-261776513
init:
- pwsh: >-
    $tagRelease = $env:appveyor_repo_tag -eq 'true'

    if ($tagRelease) {
        $tag = $env:appveyor_repo_tag_name
        Update-AppveyorBuild -Version "$tag"
    }
build_script:
- ps: msbuild .\src /t:restore,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /p:PublishRepositoryUrl=true /verbosity:minimal
test_script:
- ps: dotnet test .\src\NLog.Targets.Redis.Tests\

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: 'src\**\*.nupkg'
  - path: 'src\**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: F4Be+YAhVriUv2zHBE38iTqS55PFnxVbbNbpQDS90zqPQFgT7vVeqqQ/BGoQYhv8
  artifact: /.*(\.|\.s)nupkg/
  on:
    APPVEYOR_REPO_TAG: true
